name: face_recognition
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.6.1+4
  firebase_ml_vision: ^0.9.2+1
  export_video_frame: ^0.0.5+4
  animated_text_kit: ^2.2.0

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
